version: '3.8'
services:
  jobservice:
    build: 
      context: ./back/jobservice
      dockerfile: ./docker/dev.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./back/jobservice:/app
    command: go run .
    env_file:
      - ./back/jobservice/.env
  jobprocessor:
    build:
      context: ./back/jobprocessor
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - ./back/jobprocessor:/app
    command: go run .
    env_file:
      - ./back/jobprocessor/.env
  front:
    build:
      context: ./front
      dockerfile: ./docker/dev.Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ./front:/app
    command: pnpm run dev --host 0.0.0.0
  database:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_services
    volumes:
     - db-data:/var/lib/postgresql/data
volumes:
    db-data:
